### PR TITLE
Time parsing

### PR DESCRIPTION
**Pull request by jawr**
This isn't very backwards compatible so understandable if you do not want to merge, but this handles the parsing of time properties to `time.Time` objects. 

Also added an `update_domain.sh`as a lot of the example files were outdated. There are still some that potentially need removing, but for now am skipping them.

### CODE REVIEW

**Comment by likexian** [comment]
Hello @jawr 
Thanks for your hard works and PR.

This PR is so large and below is my opinion:
* Convert date string to time.Time is a good idea, good job.
* The examples are not expected to be updated, we need them to cover as many as possible cases but not the latest informations.
* You have change the original whois data, this is not a good idea.

**Comment by jawr** [comment]
The reason for the whois data updates is because the whois output for different servers has changed, for example some have changed their time format.

I understand that supporting legacy/existing raw data is needed, but if there are changes then which should be supported, legacy or the new format?

**Comment by likexian** [comment]
> The reason for the whois data updates is because the whois output for different servers has changed, for example some have changed their time format.
> 
> I understand that supporting legacy/existing raw data is needed, but if there are changes then which should be supported, legacy or the new format?

You are right, in this case, we need to update it manually and double check.

**Comment by jawr** [comment]
let me know what needs to be done :)

**Comment by likexian** [comment]
Thanks again for your PR, for your commits:

* add support for .fi tld
    * merged

* fixes for .fi parsing
    * merged

* add script to update examples
    * no plan to merge, need manually update and check

* fix issue with ch created_date
    * please open a new PR

* fix tests to work with new xyz raw whois (removal of nameservers from… …
    * no plan to merge, xyz do have nameservers

* refactor CreatedDat/UpdatedDate/ExpirationDate to time.Time
    * no plan to merge, date time parsing is a heavy work, it is too complex for this libary to include it, please uses third-part for date time parsing, for example: https://github.com/araddon/dateparse

* updated examples; some were using different/old date/timestamps
    * no plan to merge, as above explain

* make update_examples more robust
    * no plan to merge, as above explain

**Comment by jawr** [comment]
No problem :)

**Pull request closed without merging**
