### PR TITLE
Parse functionality for .ac.uk domains

### PR DESCRIPTION
**Pull request by dclark**
Add parsing for .ac.uk with tests for jisc.ac.uk, go files formatted.

### CODE REVIEW

**Comment by likexian** [comment]
It seems that you have replaced the `4 spaces` to `tab` in the code, It's very kind of you to take it back.

**Comment by dclark** [comment]
Hi Li

The code was passed through goimports which uses the default golang formatting.

I can take a look at changing this however best to stick to using go standard formatting?

All the best

Darren

**Comment by likexian** [comment]
Hi Darren,

Thank you very much for your pr and comment.

For the formatting, it is just `everyone has his own Hamlet`, that is no problem for you using tabs, you can keep your fork working.

Thank you.

**Comment by likexian** [comment]
Thanks.

**Pull request closed without merging**
